heat_template_version: 2015-10-15

description: |
  #### Production

  This stack is intended for low to medium traffic production
  websites and can be scaled as needed to accommodate future
  growth.  This stack includes a Cloud Load Balancer, Cloud
  Database, and a Master server (plus optional secondary
  servers).  It also includes Cloud Monitoring and Cloud
  Backups.

  This stack is running the latest version of
  [Drupal](https://www.drupal.org/),
  [nginx](https://www.nginx.com/),
  and [PHP FPM](http://php-fpm.org/).
  with a Cloud Database running
  [MySQL 5.6](http://www.mysql.com/about/).

parameter_groups:
- label: Drupal Settings
  parameters:
  - drupal_url
  - drupal_sitename
  - drupal_user
  - drupal_email
- label: rax-dev-params
  parameters:
  - secondary_template
  - ansible_source

parameters:
  #Drupal Customization
  drupal_url:
    type: string
    default: example.com
    label: Site Domain
    description: Domain to use with Drupal Site
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9.-]{1,255}.[a-zA-Z]{2,15}$"
      description: Must be a valid domain name
    immutable: true
  drupal_sitename:
    type: string
    default: Example Site
    label: Site Title
    description: Title to use for Drupal Site
    immutable: true
  drupal_user:
    type: string
    default: admin
    label: Drupal Admin Username
    description: Username for Drupal login
    constraints:
    - allowed_pattern: "^[a-zA-Z0-9]*$"
      description: Only can contain A-Z and 0-9
    immutable: true
  drupal_email:
    type: string
    default: admin@example.com
    label: Drupal Admin E-mail
    description: E-mail Address for Drupal Admin User
    immutable: true
  #Advanced Options
  server_flavor:
    type: string
    default: 4 GB General Purpose v1
    label: Server Flavor
    description: Flavor of Cloud Server to use
    constraints:
    - allowed_values:
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
    immutable: true
  database_disk:
    type: number
    default: 5
    constraints:
    - range:
        min: 5
        max: 500
    label: Database Disk (in GB)
    description: Size of the Cloud Database volume in GB
  database_flavor:
    type: string
    default: 1GB Instance
    label: Cloud Database Flavor
    description: Flavor for the Cloud Database
    constraints:
    - allowed_values:
      - 1GB Instance
      - 2GB Instance
      - 4GB Instance
      - 8GB Instance
      - 16GB Instance
      - 32GB Instance
      - 64GB Instance
  server_image:
    type: string
    default: Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM) (Orchestration)
    label: Server Image
    description: Image to be used for all servers in this stack
    constraints:
    - allowed_values:
      - Ubuntu 16.04 LTS (Xenial Xerus) (PVHVM) (Orchestration)
      - CentOS 7 (PVHVM) (Orchestration)
    immutable: true
  server_count:
    type: number
    default: 0
    label: Number of Secondary Servers
    description: Number of secondary web nodes
    constraints:
      - range: { min: 0, max: 10 }
  secondary_template:
    type: string
    default: http://catalog.rs-heat.com/drupal-small/drupal-small-secondary.yaml
    label: Secondary Template
    description: Template to use for secondary servers
    immutable: true
  ansible_source:
    type: string
    default: http://catalog.rs-heat.com/ansible-roles/ansible-roles.tar.gz
    label: Ansible Tarball
    description: The Ansible Roles will be pulled from the location provided
    immutable: true

resources:
  #Passwords
  drupal_pass:
    type: OS::Heat::RandomString
  database_pass:
    type: OS::Heat::RandomString
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true
  #Cloud Database
  drupal_database:
    type: OS::Trove::Instance
    properties:
      name:
        str_replace:
          template: stack_Database
          params:
            stack: { get_param: "OS::stack_name" }
      flavor: { get_param: database_flavor }
      size: { get_param: database_disk }
      datastore_type: mysql
      databases:
      - name: drupal
      - name: phpmyadmin
      users:
      - name: drupal
        password: { get_attr: [database_pass, value] }
        databases: [drupal, phpmyadmin]
  #Software Configurations
  upload_role_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
      - name: results
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -e
            mkdir -p /etc/ansible/roles
            wget ansible_source -O /tmp/ansible-roles.tar.gz 2>&1
            tar -xf /tmp/ansible-roles.tar.gz --strip-components=1 -C /etc/ansible/roles
          params:
            ansible_source: { get_param: ansible_source }
  drupal_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      config: |
        ---
        - name: Install and configure Drupal
          hosts: localhost
          connection: local
          roles:
          - common
          - nginx
          - php-fpm
          - composer
          - drupal
          - phpmyadmin
  other_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
      - default: "[]"
        name: lsync_servers
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_nodes
        type: CommaDelimitedList
      - default: "[]"
        name: firewall_node_rules
        type: CommaDelimitedList
      config: |
        ---
        - name: Install and configure other things
          hosts: localhost
          connection: local
          roles:
          - firewall
          - lsync
  deploy_roles:
    type: OS::Heat::SoftwareDeployment
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: upload_role_config
      server:
        get_resource: drupal_server
  deploy_drupal:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_roles
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        nginx_vhost_str: { get_param: drupal_url }
        nginx_vhost_template: "drupal"
        nginx_vhost_phpmyadmin: "True"
        tz: "America/Chicago"
        drupal_db_host: { get_attr: [drupal_database, hostname] }
        drupal_db_name: "drupal"
        drupal_db_user: "drupal"
        drupal_db_password: { get_attr: [database_pass, value] }
        drupal_domain: { get_param: drupal_url }
        drupal_user: { get_param: drupal_user }
        drupal_password: { get_attr: [drupal_pass, value] }
        phpmyadmin_host: { get_attr: [drupal_database, hostname] }
        phpmyadmin_user: "drupal"
        phpmyadmin_pass: { get_attr: [database_pass, value] }
      config:
        get_resource: drupal_config
      server:
        get_resource: drupal_server
  deploy_other:
    type: OS::Heat::SoftwareDeployment
    depends_on: deploy_drupal
    properties:
      signal_transport: TEMP_URL_SIGNAL
      input_values:
        lsync_private_key: { get_attr: [ssh_key, private_key] }
        lsync_servers:
          get_attr: [drupal_secondary, private_ip]
        firewall_global_rules: [ "0.0.0.0,0,22,tcp", "0.0.0.0,0,80,tcp", "0.0.0.0,0,443,tcp"]
        firewall_nodes: { get_attr: [drupal_secondary, private_ip] }
        firewall_node_rules: []
      config:
        get_resource: other_config
      server:
        get_resource: drupal_server
  #Master Server
  drupal_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: "OS::stack_name" }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_resource: ssh_key }
      software_config_transport: POLL_TEMP_URL
      config_drive: true
      user_data_format: SOFTWARE_CONFIG
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        build_config: "backup_agent_only,monitoring_defaults"
  #Monitoring Checks
  drupal_server_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: deploy_drupal
    properties:
      entity: { get_resource: drupal_server }
      type: remote.http
      label:
        str_replace:
          template: stack Master HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [drupal_server, accessIPv4] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [drupal_server, accessIPv4] }
      target_receiver: IPv4
  load_balancer_http_check:
    type: Rackspace::CloudMonitoring::Check
    depends_on: load_balancer
    properties:
      entity: { get_resource: drupal_server }
      type: remote.http
      label:
        str_replace:
          template: stack Load Balancer HTTP Check
          params:
            stack: { get_param: "OS::stack_name" }
      details:
        url:
          str_replace:
            template: "http://ipaddr"
            params:
              ipaddr: { get_attr: [load_balancer, PublicIp] }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
        stack-name: { get_param: "OS::stack_name" }
      period: 120
      timeout: 10
      monitoring_zones_poll:
      - Northern Virginia (IAD)
      - Chicago (ORD)
      - Dallas Fort Worth (DFW)
      - London (LON)
      target_hostname: { get_attr: [load_balancer, PublicIp] }
      target_receiver: IPv4
  #Cloud Backup
  drupal_backup:
    type: Rackspace::Cloud::BackupConfig
    depends_on: drupal_server
    properties:
      #host_ip_address: { get_attr: [drupal_server, accessIPv4] }
      server: { get_resource: drupal_server }
      BackupConfigurationName:
        str_replace:
          template: stack Weekly Backup
          params:
            stack: { get_param: "OS::stack_name" }
      Inclusions:
      - FilePath: "/var/www/"
        FileItemType: "Folder"
      NotifyFailure: true
      NotifyRecipients: { get_param: drupal_email }
      TimeZoneId: Central Standard Time
      StartTimeAmPm: AM
      StartTimeHour: 1
      StartTimeMinute: 0
      HourInterval: null
      DayOfWeekId: 0
      Frequency: "Weekly"
      VersionRetention: 30
  #Secondary Server
  drupal_secondary:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: { get_param: secondary_template }
        properties:
          ssh_key: { get_resource: ssh_key }
          parent_stack_id: { get_param: "OS::stack_id" }
          server_image: { get_param: server_image }
          server_flavor: { get_param: server_flavor }
          apache_default_domain: { get_param: drupal_url }
          master_server: { get_attr: [ drupal_server, networks, private, 0] }
          server_name:
            str_replace:
              template: stack-secondary-%index%
              params:
                stack: { get_param: "OS::stack_name" }
          ansible_source: { get_param: ansible_source }
  #Cloud Load Balancer
  load_balancer:
    type: Rackspace::Cloud::LoadBalancer
    depends_on:
    - deploy_drupal
    - drupal_secondary
    properties:
      name:
        str_replace:
          template: stack_Load_Balancer
          params:
            stack: { get_param: "OS::stack_name" }
      nodes:
      - addresses: [ { get_attr: [drupal_server, networks, private, 0] } ]
        port: 80
        condition: ENABLED
      - addresses: { get_attr: [drupal_secondary, private_ip] }
        port: 80
        condition: ENABLED
      port: 80
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: ENABLED
      sessionPersistence: HTTP_COOKIE
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

outputs:
  drupal_login_user:
    description: Drupal Admin User
    value:
      get_param: drupal_user
  drupal_login_password:
    description: Drupal Admin Password
    value:
      get_attr: [drupal_pass, value]
  drupal_public_ip:
    description: Load Balancer IP
    value:
      get_attr: [load_balancer, PublicIp]
  drupal_admin_url:
    description: Drupal Admin URL
    value:
      str_replace:
        template: "https://domain/admin/"
        params:
          domain: { get_param: drupal_url }
  drupal_public_url:
    description: Drupal Public URL
    value:
      str_replace:
        template: "http://domain/"
        params:
          domain: { get_param: drupal_url }
  phpmyadmin_url:
    description: PHPMyAdmin URL
    value:
      str_replace:
        template: "https://IP/phpmyadmin/"
        params:
          IP:
            get_attr: [drupal_server, accessIPv4]
  mysql_user:
    description: Database User
    value: "drupal"
  mysql_password:
    description: Database Password
    value:
      get_attr: [database_pass, value]
  ssh_private_key:
    description: SSH Private Key
    value:
      get_attr: [ssh_key, private_key]
  server_ip:
    description: Server Public IP
    value:
      get_attr: [drupal_server, accessIPv4]
  secondary_ips:
    description: Secondary Node IPs
    value:
      get_attr: [drupal_secondary, public_ip]
